# Generated by Django 4.2.1 on 2023-06-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upimg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
